spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    baseline-version: 1

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/redirect"
            scope: openid, profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    forward-headers-strategy: framework

app:
  frontend:
    url: ${APP_FRONTEND_URL:http://localhost:3000}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:lNjYbLAq4CVPcrRpJEq3QZID6cXifMeoiIpsh8szUfrvgHVBFab3r1aX1PfdBP5p}
