spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    baseline-version: 1

  app:
    frontend:
      url: http://localhost:3000


  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    forward-headers-strategy: framework

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

app:
  cookie:
    domain: ${APP_COOKIE_DOMAIN}
    max-age: ${APP_COOKIE_MAX_AGE:900}   # default 15min = 900s
    secure: ${APP_COOKIE_SECURE:false}
